server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion:
      - non_null
      - non_empty

  flyway:
    baseline-on-migrate: true
    clean-disabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: "jdbc:postgresql://localhost:5432/wutsi-security"
    username: "postgres"
    password: "postgres"
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      idle-timeout: 10000 #maximum idle time for connection
      minimum-idle: 8 #minimum number of idle connections maintained by HikariCP in a connection pool
      minimum-pool-size: 8 #maximum pool size
      maximum-pool-size: 8 #maximum pool size
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.

wutsi:
  application-name: "wutsi-security"
  platform:
    cache:
      type: "local"
    stream:
      name: "${wutsi.application-name}"
      type: "local"
    tracing:
      client-id: "${wutsi.application-name}"
      device-id-provider:
        type: "header"

  memcached:
    enabled: false
    username: ${MEMCACHIER_USERNAME}
    password: ${MEMCACHIER_PASSWORD}
    servers: ${MEMCACHIER_SERVERS}
    ttl: ${SPRING_CACHE_TTL:86400}
  rabbitmq:
    enabled: false
    url: ${CLOUDAMQP_URL}
    thread-pool-size: 8
    max-retries: 10
    queue-ttl-seconds: 86400       # 24 heures
    replay-cron: "0 */15 * * * *"  # Replay DLQ every 15 mins

logging:
  level:
    root: INFO
    com.wutsi.platform.security: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"

