openapi: "3.0.0"
info:
  title: "Wutsi Security Server"
  description: |
    Wutsi Security Server. It provides the following features:

    - [JWT](https://jwt.io) authentication
    - Application registration
  version: "1.0.0"

servers:
  - url: https://wutsi-server-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-server-server-prod.herokuapp.com
    description: Production

paths:
  /v1/keys:
    get:
      operationId: "get-key"
      description: |
        Return the current server's key.
        This key can be used for:
          - decrypting messages
          - verifying signatures
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetKeyResponse'
      tags:
        - Security

    post:
      operationId: "create-key"
      description: |
        Create the server's key.
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateKeyResponse'
      tags:
        - Security

  /v1/scopes:
    get:
      operationId: "search-scopes"
      description: |
        Return all the security scopes
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchScopeResponse'
      tags:
        - Security

components:
  schemas:
    CreateKeyResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the key created

    GetKeyResponse:
      type: object
      properties:
        key:
          type: object
          $ref: "#/components/schemas/Key"

    Key:
      type: object
      properties:
        algorithm:
          type: string
          description: Name of the security algorithm
        content:
          type: string
          description: Content of the key, based-64 encoded


    SearchScopeResponse:
      type: object
      properties:
        scopes:
          type: array
          items:
            $ref: "#/components/schemas/Scope"
    Scope:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID of the scope
        name:
          type: string
          description: Name of the scope
        description:
          type: string
          description: Description of the scope
          nullable: true
        securityLevel:
          type: integer
          description: Security Level required to get this scope
